In [2]:
%pip install pandas

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("popular_people.csv")
df

,name,gender,known_for_department,original_name,popularity
0,Eric Larson,2,Visual Effects,Eric Larson,47.9780
1,Robert Middlemass,2,Acting,Robert Middlemass,47.8017
2,María Vaner,1,Acting,María Vaner,47.2016
3,Carl Wharton,2,Acting,Carl Wharton,36.3365
4,Victor Moore,2,Acting,Victor Moore,35.9181
...,...,...,...,...,...
9975,Tamu Blackwell,1,Acting,Tamu Blackwell,1.0432
9976,Yoshio Urasawa,2,Writing,浦沢義雄,1.1777
9977,Miko Hughes,2,Acting,Miko Hughes,1.5346
9978,Phoebe Fox,1,Acting,Phoebe Fox,1.1656
9979,Debora Calì,1,Acting,Debora Calì,1.2658

dropar uma coluna

In [5]:
df = df.drop(columns = ["original_name", "gender"])
df

                   name known_for_department  popularity
0           Eric Larson       Visual Effects     47.9780
1     Robert Middlemass               Acting     47.8017
2           María Vaner               Acting     47.2016
3          Carl Wharton               Acting     36.3365
4          Victor Moore               Acting     35.9181
...                 ...                  ...         ...
9975     Tamu Blackwell               Acting      1.0432
9976     Yoshio Urasawa              Writing      1.1777
9977        Miko Hughes               Acting      1.5346
9978         Phoebe Fox               Acting      1.1656
9979        Debora Calì               Acting      1.2658

[9980 rows x 3 columns]

para ler as primeiras linhas do banco de dados

In [6]:
df.head()

                name known_for_department  popularity
0        Eric Larson       Visual Effects     47.9780
1  Robert Middlemass               Acting     47.8017
2        María Vaner               Acting     47.2016
3       Carl Wharton               Acting     36.3365
4       Victor Moore               Acting     35.9181

para ver quanto uma tabela ocupa de memoria, faz um raio x completo, mostrando a estrutura interna

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9980 entries, 0 to 9979
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   name                  9980 non-null   string
 1   known_for_department  9975 non-null   str
 2   popularity            9980 non-null   float32
dtypes: float32(1), str(1), string(1)
memory usage: 382.2 KB

df.info faz uma estimativa rapida, para fazer uma busca profunda de toda a estrutura

In [19]:
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 9980 entries, 0 to 9979
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   name                  9980 non-null   string
 1   known_for_department  9975 non-null   str
 2   popularity            9980 non-null   float32
dtypes: float32(1), str(1), string(1)
memory usage: 382.2 KB

acima da para ver a diferença, quando antes apontava 312kb agora apontou 1,8mb

para ir direto ao ponto e mostrar quantos bytes cada coluna individual está gastando na memória RAM.

In [20]:
df.memory_usage(deep=True)

Index                      132
name                    208924
known_for_department    142443
popularity               39920
dtype: int64

para saber os dados que foram escritos em uma coluna, sem repetição

In [39]:
df["gender"].unique()

array([2, 1, 0, 3])

In [11]:
df["known_for_department"].unique()

<ArrowStringArray>
[   'Visual Effects',            'Acting',         'Directing',
           'Writing',           'Editing',        'Production',
          'Lighting',             'Sound',            'Camera',
              'Crew',               'Art',           'Creator',
 'Costume & Make-Up',                 nan]
Length: 14, dtype: str

para tratar os dados e alterar o tipo da variavel

In [ ]:
df["gender"] = df["gender"].map({0: "Not Set", 1: "Female", 2: "Male", 3: "Non-Binary"}).astype("category")

In [13]:
df["known_for_department"].map({"Acting": "Arts", "Directing": "Arts", "Production": "Arts", "Writing": "Arts", "Creator": "Arts", "Sound": "Technical", "Camera": "Technical", "Visual Effects": "Technical", "Editing": "Technical", "Art": "Technical", "Costume & Make-Up": "Technical", "Crew": "Technical", "Lighting": "Technical"}).fillna("Other").astype("category")

0       Technical
1            Arts
2            Arts
3            Arts
4            Arts
          ...
9975         Arts
9976         Arts
9977         Arts
9978         Arts
9979         Arts
Name: known_for_department, Length: 9980, dtype: category
Categories (3, str): ['Arts', 'Other', 'Technical']

In [101]:
pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-24.0.0-cp314-cp314-win_amd64.whl.metadata (3.0 kB)
Downloading pyarrow-24.0.0-cp314-cp314-win_amd64.whl (28.0 MB)
   ---------------------------------------- 0.0/28.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/28.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/28.0 MB ? eta -:--:--
    --------------------------------------- 0.5/28.0 MB 1.3 MB/s eta 0:00:22
   - -------------------------------------- 1.0/28.0 MB 2.2 MB/s eta 0:00:13
   - -------------------------------------- 1.3/28.0 MB 2.0 MB/s eta 0:00:14
   - -------------------------------------- 1.3/28.0 MB 2.0 MB/s eta 0:00:14
   - -------------------------------------- 1.3/28.0 MB 2.0 MB/s eta 0:00:14
   - -------------------------------------- 1.3/28.0 MB 2.0 MB/s eta 0:00:14
   - -------------------------------------- 1.3/28.0 MB 2.0 MB/s eta 0:00:14
   -- ------------------------------------- 1.6/28.0 MB 792.7 kB/s eta 0:00:34
   -- ------------------------------------- 2.1/28.0 MB 966.0 kB/s eta 0:00:27
   --- ------------------------------------ 2.6/28.0 MB 1.1 MB/s eta 0:00:23
   ---- ----------------------------------- 3.4/28.0 MB 1.3 MB/s eta 0:00:19
   ----- ---------------------------------- 3.9/28.0 MB 1.5 MB/s eta 0:00:17
   ------- -------------------------------- 5.0/28.0 MB 1.7 MB/s eta 0:00:14
   -------- ------------------------------- 6.0/28.0 MB 2.0 MB/s eta 0:00:12
   --------- ------------------------------ 6.8/28.0 MB 2.1 MB/s eta 0:00:11
   ----------- ---------------------------- 7.9/28.0 MB 2.3 MB/s eta 0:00:09
   ------------ --------------------------- 8.9/28.0 MB 2.4 MB/s eta 0:00:08
   ------------- -------------------------- 9.7/28.0 MB 2.5 MB/s eta 0:00:08
   --------------- ------------------------ 10.7/28.0 MB 2.6 MB/s eta 0:00:07
   ----------------- ---------------------- 12.1/28.0 MB 2.8 MB/s eta 0:00:06
   ------------------ --------------------- 12.8/28.0 MB 2.9 MB/s eta 0:00:06
   ------------------- -------------------- 13.9/28.0 MB 3.0 MB/s eta 0:00:05
   -------------------- ------------------- 14.4/28.0 MB 2.9 MB/s eta 0:00:05
   ---------------------- ----------------- 15.5/28.0 MB 3.0 MB/s eta 0:00:05
   ---------------------- ----------------- 15.7/28.0 MB 3.0 MB/s eta 0:00:05
   ---------------------- ----------------- 15.7/28.0 MB 3.0 MB/s eta 0:00:05
   ---------------------- ----------------- 15.7/28.0 MB 3.0 MB/s eta 0:00:05
   ---------------------- ----------------- 16.0/28.0 MB 2.7 MB/s eta 0:00:05
   ----------------------- ---------------- 16.5/28.0 MB 2.7 MB/s eta 0:00:05
   ------------------------- -------------- 17.6/28.0 MB 2.8 MB/s eta 0:00:04
   ------------------------- -------------- 18.1/28.0 MB 2.8 MB/s eta 0:00:04
   -------------------------- ------------- 18.9/28.0 MB 2.8 MB/s eta 0:00:04
   ---------------------------- ----------- 19.9/28.0 MB 2.8 MB/s eta 0:00:03
   ----------------------------- ---------- 20.7/28.0 MB 2.9 MB/s eta 0:00:03
   ------------------------------ --------- 21.5/28.0 MB 2.9 MB/s eta 0:00:03
   -------------------------------- ------- 22.8/28.0 MB 3.0 MB/s eta 0:00:02
   ---------------------------------- ----- 23.9/28.0 MB 3.1 MB/s eta 0:00:02
   ----------------------------------- ---- 24.9/28.0 MB 3.1 MB/s eta 0:00:01
   ----------------------------------- ---- 24.9/28.0 MB 3.1 MB/s eta 0:00:01
   ----------------------------------- ---- 24.9/28.0 MB 3.1 MB/s eta 0:00:01
   ------------------------------------- -- 26.2/28.0 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------  27.8/28.0 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------- 28.0/28.0 MB 3.1 MB/s  0:00:09
Installing collected packages: pyarrow
Successfully installed pyarrow-24.0.0
Note: you may need to restart the kernel to use updated packages.

In [14]:
df["name"] = df["name"].astype("string[pyarrow]")

In [15]:
df["popularity"] = df["popularity"].astype("float32")

para descrever a qntd de dados, media, valor min, valor max em cada coluna

In [17]:
df.describe()

        popularity
count  9980.000000
mean      2.123684
std       1.893017
min       0.578400
25%       1.358150
50%       1.647000
75%       2.209725
max      47.978001

Para salvar o novo arquivo otimizado em csv

In [ ]:
df.to_excel("popular_people_otimizado.xlsx", index=False)

In [23]:
df.to_csv("popular_people_otimizado.csv", index=False)